networks:
  local:

volumes:
  pdata:
  static:
  media:

services:    
  postgredb:
    image: postgres:13.9
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pdata:/var/lib/postgresql/data
      - ./docker/postgresql/docker-entrypoint-initdb.d/psql_dump.sql:/docker-entrypoint-initdb.d/psql_dump.sql
    env_file:
      - .env
    networks:
      - local

  nginx:
     image: nginx:latest
     restart: always
     ports:
       - "80:80"
     volumes:
       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
       - ./static:/src/static
       - ./media:/src/media
     networks:
       - local

  vcrm:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      WAIT_HOSTS: postgredb:5432
    networks:
      - local
    volumes:
      - .:/src
      - ./static:/src/static
      - ./media:/src/media
