# Generated by Django 4.1.7 on 2023-04-11 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Заголовок')),
                ('hours_cost', models.DecimalField(decimal_places=1, default=0.5, max_digits=3, verbose_name='Трудозатраты в часах')),
                ('status', models.CharField(choices=[('Новая', 'Новая'), ('В работе', 'В работе'), ('Выполнена', 'Выполнена'), ('Отложена', 'Отложена'), ('Не задача', 'Не задача')], default='Новая', max_length=30, verbose_name='Статус')),
                ('description', tinymce.models.HTMLField(null=True, verbose_name='Описание')),
                ('fire', models.BooleanField(default=False, verbose_name='Срочная')),
                ('drive', models.BooleanField(default=False, verbose_name='С выездом')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_closed', models.DateTimeField(null=True, verbose_name='Дата закрытия')),
                ('contacts', models.CharField(blank=True, max_length=90, null=True, verbose_name='Контакты')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_client', to='clients.client', verbose_name='Клиент')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_performer', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', tinymce.models.HTMLField(verbose_name='Комментарий')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_performer', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_task', to='tasks.task')),
            ],
            managers=[
                ('user_comments', django.db.models.manager.Manager()),
            ],
        ),
    ]
