# Generated by Django 4.2.1 on 2023-05-15 12:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('last_activity', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последняя активность')),
                ('web_site', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=254, null=True, verbose_name='Адрес')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Обслуживаем')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Список клиентов',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=120, unique=True, verbose_name='Контакт')),
                ('fio', models.CharField(blank=True, max_length=120, null=True, verbose_name='ФИО')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('last_activity', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последняя активность')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Список контактов',
            },
        ),
    ]
