# Generated by Django 4.2.1 on 2023-05-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageid', models.IntegerField(unique=True, verbose_name='id')),
                ('from_name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('to', models.CharField(max_length=255, null=True, verbose_name='Кому')),
                ('cc', models.CharField(max_length=255, null=True, verbose_name='Копия')),
                ('date', models.DateField(verbose_name='Дата')),
                ('subject', models.CharField(default='(Без темы)', max_length=255, verbose_name='Тема')),
                ('text_html', models.TextField(null=True, verbose_name='Текст')),
                ('server_messageid', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Почта',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='mail_media', verbose_name='Вложение')),
                ('inline', models.BooleanField(default=False, verbose_name='В письме')),
                ('mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.mail')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Список вложений к почте',
            },
        ),
    ]
